services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: httpclient_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    depends_on:
      - httpbin

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpclient_httpbin
    restart: unless-stopped
